title: Juan Vega
logo: /images/foto.jpeg
description: STRUCTURAL / BIM SPECIALIST
message: Ingeniero Civil de la Universidad Nacional de Ingeniería, CIP N°235493. Con certificación ACP-Revit Structure. Apasionado con el Diseño Estructural, Metodología BIM-VDC y Automatización de procesos.
show_downloads: false
theme: jekyll-theme-minimal
