title: Juan Vega
logo: /images/foto.jpeg
description: STRUCTURAL / BIM SPECIALIST
description: Ingeniero Civil de la Universidad Nacional de Ingeniería, Titulado y Colegiado con CIP N°235493. Con certificación ACP-Revit Structure y cursando actualmente el Master Internacional en BIM en Infraestructuras de EADIC.
description: Apasionado con el Diseño Estructural, Metodología BIM-VDC y Automatización de procesos.
description: Soy BIM Manager en proyectos de infraestructura de gran envergadura, tales como Puentes, Muros de contención, Obras de Drenaje Transversal, Drenaje Pluvial, entre otros.Además, me desempeño como docentes en cursos de modelamiento BIM con Revit y Tekla aplicado a Infraestructuras, y cursos relacionados a la automatización de procesos como Dynamo para Civil 3D, Modelamiento con Tekla y Grasshopper, entre otros.
show_downloads: true
theme: jekyll-theme-minimal
